apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expiring-deployments.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "expiring-deployments.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations: {}
data:
  values.json: |
    {
      "schedule": {{ .Values.schedule | quote }},
      "dryRun": {{ ternary "true" "false" .Values.dryRun | quote }},
      "features": {{ toJson .Values.features }},
      "selectors": {{ toJson .Values.selectors }},
      "safety": {{ toJson .Values.safety }},
      "helm": {{ toJson .Values.helm }}
    }
